### ISSUE TITLE
NPE for included config with combined origins

### ISSUE THREAD

**Issue by radist-nt** [gnieh/logback-config#13]
1. Append file `includedConfig.conf` with the following content to the src/test/resources:
```
include "./asyncAppender.conf"
test.logback {
}
```
2. Modify file name in the first line of `org.gnieh.logback.config.ConfigConfiguratorTest.testConfigureAsyncAppender()` to `includedConfig.conf`
3. Run tests.

Expected results: passing tests
Actual results:
```
java.lang.NullPointerException
	at ch.qos.logback.core.joran.spi.ConfigurationWatchList.convertToFile(ConfigurationWatchList.java:93)
	at ch.qos.logback.core.joran.spi.ConfigurationWatchList.addAsFileToWatch(ConfigurationWatchList.java:59)
	at ch.qos.logback.core.joran.spi.ConfigurationWatchList.addToWatchList(ConfigurationWatchList.java:67)
	at ch.qos.logback.core.joran.util.ConfigurationWatchListUtil.addToWatchList(ConfigurationWatchListUtil.java:68)
	at org.gnieh.logback.config.ConfigConfigurator.lambda$2(ConfigConfigurator.java:342)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at org.gnieh.logback.config.ConfigConfigurator.registerFileWatchers(ConfigConfigurator.java:342)
	at org.gnieh.logback.config.ConfigConfigurator.configure(ConfigConfigurator.java:163)
	at org.gnieh.logback.config.ConfigConfiguratorTest.testConfigureAsyncAppender(ConfigConfiguratorTest.java:139)
...............
```

The problem is `org.gnieh.logback.config.ConfigConfigurator.getSourceFiles(ConfigValue, Set<URL>)`. It's to naive to work as expected. The only valid way to gather files in current config library implementation is to provide the `ConfigIncluder` implementation to `ConfigParseOptions.prependIncluder` and pass the result to the one of `ConfigFactory` static methods.

**Comment by radist-nt** [comment]
Do you plan to publish a minor release with pull request #14 ?
